/**
 * Utility to check for and load saved measurements from syncforge directory
 */

/**
 * Check if saved measurements exist for a study/series
 * @param {string} studyInstanceUID
 * @param {string} seriesInstanceUID - Optional
 * @returns {Promise<Array>} Array of saved CSV files
 */
export async function checkSavedMeasurements(studyInstanceUID, seriesInstanceUID = null) {
  try {
    const params = new URLSearchParams({ studyInstanceUID });
    if (seriesInstanceUID) {
      params.append('seriesInstanceUID', seriesInstanceUID);
    }

    const response = await fetch(
      `http://localhost:3001/api/syncforge/list-csv?${params.toString()}`
    );

    if (response.ok) {
      const data = await response.json();
      return data.files || [];
    }
    return [];
  } catch (error) {
    console.warn('⚠️ Could not check for saved measurements:', error.message);
    return [];
  }
}

/**
 * Load a specific CSV file content
 * @param {string} studyInstanceUID
 * @param {string} seriesInstanceUID
 * @param {string} filename
 * @returns {Promise<string|null>} CSV content or null
 */
export async function loadMeasurementCSV(studyInstanceUID, seriesInstanceUID, filename) {
  try {
    const params = new URLSearchParams({
      studyInstanceUID,
      seriesInstanceUID,
      filename,
    });

    const response = await fetch(
      `http://localhost:3001/api/syncforge/get-csv?${params.toString()}`
    );

    if (response.ok) {
      const data = await response.json();
      return data.csvContent;
    }
    return null;
  } catch (error) {
    console.error('❌ Error loading CSV:', error);
    return null;
  }
}

/**
 * Parse CSV content to extract measurement data
 * Note: This is a simplified parser. Real implementation should match
 * the exact format generated by downloadCSVReport.js
 *
 * @param {string} csvContent
 * @returns {Array<Object>} Parsed measurements
 */
export function parseCSVMeasurements(csvContent) {
  if (!csvContent) return [];

  const lines = csvContent.trim().split('\n');
  if (lines.length < 2) return []; // Need at least header + 1 row

  const headers = lines[0].split(',');
  const measurements = [];

  for (let i = 1; i < lines.length; i++) {
    const values = lines[i].split(',');
    const measurement = {};

    headers.forEach((header, index) => {
      measurement[header.trim()] = values[index]?.trim() || '';
    });

    measurements.push(measurement);
  }

  return measurements;
}

/**
 * Show prompt asking user if they want to load saved measurements
 * @param {Object} uiNotificationService
 * @param {Array} savedFiles
 * @param {Function} onLoad - Callback when user clicks load
 */
export function promptLoadMeasurements(uiNotificationService, savedFiles, onLoad) {
  if (!savedFiles || savedFiles.length === 0) return;

  const fileCount = savedFiles.length;
  const message =
    fileCount === 1
      ? `Found 1 saved measurement file: ${savedFiles[0].filename}`
      : `Found ${fileCount} saved measurement files`;

  uiNotificationService.show({
    title: 'Saved Measurements Available',
    message: message,
    type: 'info',
    duration: 10000, // 10 seconds
    actions: [
      {
        type: 'primary',
        text: 'Load',
        onClick: () => {
          console.log('📂 User chose to load saved measurements');
          onLoad(savedFiles);
        },
      },
      {
        type: 'secondary',
        text: 'Skip',
        onClick: () => {
          console.log('⏭️ User chose to skip loading measurements');
        },
      },
    ],
  });
}

export default {
  checkSavedMeasurements,
  loadMeasurementCSV,
  parseCSVMeasurements,
  promptLoadMeasurements,
};

